name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: "yarn"
          cache-dependency-path: |
            yarn.lock
            package.json
            apps/**/package.json
            packages/**/package.json

      - name: Install dependencies
        run: yarn

      - name: Generate the TypeScript models from OpenAPI specs
        run: yarn workspaces foreach run generate:api-models

      - name: Build all projects
        run: yarn build

      - name: TMP Status Before
        run: yarn changeset status

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish: yarn changeset tag && yarn chageset publish
          createGithubReleases: true

      - name: TMP Status After
        run: yarn changeset status

      - name: Publish
        # if: steps.changesets.outputs.hasChangesets
        # You can do something when a publish should happen.
        run: echo "${{toJSON(steps.changesets.outputs)}}"
